### PR TITLE
Reformat output

### PR DESCRIPTION
**Pull request by aroelo**
- The output from the new and old platform of OAPEN is changed so that the format and schema is the same for both of them.
This will make it easier to handle the data in BigQuery, the reasoning is discussed in the issue here: https://github.com/The-Academic-Observatory/observatory-platform/issues/424

- Each row represents 1 book, the location metrics (both for the country and location from IP) are nested within this row. Previously, each row represented a combination of book + location and there was no nested data.

- For the old platform, both the Country and IP reports are now downloaded and then merged. Previously, only the IP report was downloaded. 

- For the new platform, the API is queried 3 times, each time with different 'attributes_to_show'. The results from these 3 queries are then merged. The queries are:
    - Once without any attributes to show
    - Once with 'Country' as an attribute to show
    - Once with 'Client_IP' as an attribute to show.

- An extra field 'version' is added, referring to the COUNTER version of the reports. This is version 4 for the old platform and version 5 for the new platform.

### CODE REVIEW

**Review by jdddog — COMMENTED** [review]
It looks good Aniek. When I ran it there was one error that occurred, for the last month that was processed: "in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'":
```python
Toapen_access_statssvu7nvx1la80 Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
```

**Comment by aroelo** [comment]
> It looks good Aniek. When I ran it there was one error that occurred, for the last month that was processed: "in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'":
> 
> ```python
> Toapen_access_statssvu7nvx1la80 Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> ```

Apparently the data for the complete month of May is not available yet (at least today on 2021-06-01). I'm not quite sure when the data becomes available. I assume if we query data from 2 months before the start date (so 1 month before the execution date) we will be safe. Would this be okay or is this too much delay?

It might be available just 1 or 2 days later and we could adjust the start date, but I don't know that right now as well as whether it will be the same date every month.

**Comment by jdddog** [comment]
> > It looks good Aniek. When I ran it there was one error that occurred, for the last month that was processed: "in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'":
> > ```python
> > Toapen_access_statssvu7nvx1la80 Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> > Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> > ```
> 
> Apparently the data for the complete month of May is not available yet (at least today on 2021-06-01). I'm not quite sure when the data becomes available. I assume if we query data from 2 months before the start date (so 1 month before the execution date) we will be safe. Would this be okay or is this too much delay?
> 
> It might be available just 1 or 2 days later and we could adjust the start date, but I don't know that right now as well as whether it will be the same date every month.

Maybe we could run have this DAG run on the second Sunday of the month?

**Comment by aroelo** [comment]
> > > It looks good Aniek. When I ran it there was one error that occurred, for the last month that was processed: "in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'":
> > > ```python
> > > Toapen_access_statssvu7nvx1la80 Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> > > Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> > > ```
> > 
> > 
> > Apparently the data for the complete month of May is not available yet (at least today on 2021-06-01). I'm not quite sure when the data becomes available. I assume if we query data from 2 months before the start date (so 1 month before the execution date) we will be safe. Would this be okay or is this too much delay?
> > It might be available just 1 or 2 days later and we could adjust the start date, but I don't know that right now as well as whether it will be the same date every month.
> 
> Maybe we could run have this DAG run on the second Sunday of the month?

Let's see when the data is available, I didn't notice this yesterday but in the error message it says `'Last date processed is 2021-04-30'`, I'm not sure if they process it on a per day basis or per month, but 2021-04-30 is a whole month back, so I'm not sure if it will be available already at the second Sunday of the month.

I did add some extra checks to look for these errors/exceptions that are in the report header. Perhaps we could merge this PR and all we need to do later is update the cron expression in the telescope. 
We can also update the hash/release of the cloud function when changing the cron expression.

**Comment by jdddog** [comment]
> > > > It looks good Aniek. When I ran it there was one error that occurred, for the last month that was processed: "in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'":
> > > > ```python
> > > > Toapen_access_statssvu7nvx1la80 Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> > > > Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 65, in download download_access_stats_new(file_path, release_date, username, password, publisher_uuid, geoip_client) File "/user_code/main.py", line 236, in download_access_stats_new assert len(base_json['Report_Items']) == len(ip_json['Report_Items']) == len(country_json['Report_Items']) KeyError: 'Report_Items'
> > > > ```
> > > 
> > > 
> > > Apparently the data for the complete month of May is not available yet (at least today on 2021-06-01). I'm not quite sure when the data becomes available. I assume if we query data from 2 months before the start date (so 1 month before the execution date) we will be safe. Would this be okay or is this too much delay?
> > > It might be available just 1 or 2 days later and we could adjust the start date, but I don't know that right now as well as whether it will be the same date every month.
> > 
> > 
> > Maybe we could run have this DAG run on the second Sunday of the month?
> 
> Let's see when the data is available, I didn't notice this yesterday but in the error message it says `'Last date processed is 2021-04-30'`, I'm not sure if they process it on a per day basis or per month, but 2021-04-30 is a whole month back, so I'm not sure if it will be available already at the second Sunday of the month.
> 
> I did add some extra checks to look for these errors/exceptions that are in the report header. Perhaps we could merge this PR and all we need to do later is update the cron expression in the telescope.
> We can also update the hash/release of the cloud function when changing the cron expression.

Yeah that sounds good.

**Pull request merged**
